### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kadnan** [remaudcorentin-dev/python-allrecipes#1]
Nothing is being printed. Most probably HTML got changed

**Comment by ranaq** [comment]
I'm having the same problem. query_results is empty no matter what I put in

**Comment by ChenchaoZhao** [comment]
same problem. empty result.

**Comment by mattyx96** [comment]
Same here

**Comment by remaudcorentin-dev** [comment]
Fixed in version 0.2.1
`pip install python-allrecipes==0.2.1` should solve your issues.
