### ISSUE TITLE
Error in __init.py__, line 34, in search

### ISSUE THREAD

**Issue by manastitious** [remaudcorentin-dev/python-allrecipes#4]
I am getting the following error:
`
py main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    query_result = AllRecipes.search(query_options)
  File "E:\ProgramData\GitHub\python-allrecipes\allrecipes\__init__.py", line 34, in search
    next(iterarticles)
StopIteration
`

Currently, I am using python 3.8

**Comment by brentwilder** [comment]
Same error as above is also present when I run it on  python 3.7

**Comment by sudhanvalalit** [comment]
I had the same issue. I wrote a scraper based on the same keywords. You can check it out here:
https://github.com/sudhanvalalit/ML_projects/tree/master/all_recipes

I hope this helps.

**Comment by emel-kayaci** [comment]
Thank you @sudhanvalalit. I tried your code.  It worked exactly as I wanted!

I only had to change this line as I got the NoneType value error.
`resp = str(self.soup.find('span', class_="search-results-total-results")).strip(' ')`

Also, I changed the query URL to be able to add more than one ingredient to the recipe.
`query_url = urllib.parse.urlencode(self.query_dict, doseq=True)`

**Comment by remaudcorentin-dev** [comment]
Fixed on version 0.3.1
